Take vars to the brackets

diff --git a/img-tool b/img-tool
--- a/img-tool
+++ b/img-tool
@@ -300,27 +300,27 @@ size() {
   IMG_PATH=${1}
   NEW_IMG_SIZE=${2}
 
-  [ -e $IMG_PATH ] || (my_echo "The file path doesn't exist!" "RED"; exit 1)
-  [ -f $IMG_PATH ] || (my_echo "The file path isn't a file! Now 'size' utility doesn't support working with devices." "RED"; exit 1)
+  [ -e ${IMG_PATH} ] || (my_echo "The file path doesn't exist!" "RED"; exit 1)
+  [ -f ${IMG_PATH} ] || (my_echo "The file path isn't a file! Now 'size' utility doesn't support working with devices." "RED"; exit 1)
 
   # TODO: Check OS and current software
   # For example check macOS
 
   FDISK_INFO=$(fdisk -l ${IMG_PATH}) && echo -e "${FDISK_INFO}"
   # https://raspberrypi.stackexchange.com/questions/13137/how-can-i-mount-a-raspberry-pi-linux-distro-image
-  # Or we can use: "parted -m $IMG_PATH unit B print free", but it have not DISKID
+  # Or we can use: "parted -m ${IMG_PATH} unit B print free", but it have not DISKID
   # https://ru.wikipedia.org/wiki/Разрежённый_файл
 
-  CUR_DISKID=$(echo -e "$FDISK_INFO" | sed -n 's/Disk identifier: 0x\([^ ]*\)/\1/p')
+  CUR_DISKID=$(echo -e "${FDISK_INFO}" | sed -n 's/Disk identifier: 0x\([^ ]*\)/\1/p')
 
-  LINUX_PART=$(echo -e "$FDISK_INFO" | tail -1 | grep Linux)
-  [[ -z $LINUX_PART ]] && (my_echo "Linux partition is not at the end!" "RED"; exit 1)
-  LINUX_PART_START=$(($(echo $LINUX_PART | awk -F' ' '{ print $2 }') * 512))
-  LINUX_PART_END=$(($(echo $LINUX_PART | awk -F' ' '{ print $3 }') * 512))
+  LINUX_PART=$(echo -e "${FDISK_INFO}" | tail -1 | grep Linux)
+  [[ -z ${LINUX_PART} ]] && (my_echo "Linux partition is not at the end!" "RED"; exit 1)
+  LINUX_PART_START=$(($(echo ${LINUX_PART} | awk -F' ' '{ print $2 }') * 512))
+  LINUX_PART_END=$(($(echo ${LINUX_PART} | awk -F' ' '{ print $3 }') * 512))
 
   # Можно делать луп на 2ю партицию просто используя "${LOOPBACK}p2",
   # но тут проверочки и другие полезные данные
-  LOOPBACK=`losetup -f` && losetup $LOOPBACK -o "$LINUX_PART_START" "$IMG_PATH"
+  LOOPBACK=`losetup -f` && losetup ${LOOPBACK} -o "${LINUX_PART_START}" "${IMG_PATH}"
   # https://www.stableit.ru/2011/05/losetup.html
   # -f     : losetup сам выбрал loop (минуя занятые) - отказался чтобы образ был размещен,
   # только на определенном раньше LOOPBACK (--show работает не везде)
@@ -333,87 +333,87 @@ size() {
   # Change image size to 512B diveded size
   # https://stackoverflow.com/questions/26540693/how-do-i-read-write-a-block-device
 
-  e2fsck -fy -v $LOOPBACK &> /dev/null || (my_echo "e2fsck changed the image. Maybe he is broken. Try again." "RED"; exit 1;)
+  e2fsck -fy -v ${LOOPBACK} &> /dev/null || (my_echo "e2fsck changed the image. Maybe he is broken. Try again." "RED"; exit 1;)
 
-  local LINUX_PART_MIN_SIZE=$(( $(resize2fs -P $LOOPBACK 2> /dev/null | awk -F': ' '{ print $2 }') * 4096 ))
-  losetup -d "$LOOPBACK"
+  local LINUX_PART_MIN_SIZE=$(( $(resize2fs -P ${LOOPBACK} 2> /dev/null | awk -F': ' '{ print $2 }') * 4096 ))
+  losetup -d "${LOOPBACK}"
 
-  local IMG_MIN_SIZE=$(($LINUX_PART_START + $LINUX_PART_MIN_SIZE + 512))
-  local CUR_IMG_SIZE=$(($LINUX_PART_END + 512))
-  local OBJ_IMG_SIZE=`du -sb $IMG_PATH | awk -F' ' '{ print $1 }'` # https://prowebmastering.ru/linux-uznat-razmer-papok-i-failov-v-terminale.html
+  local IMG_MIN_SIZE=$((${LINUX_PART_START} + ${LINUX_PART_MIN_SIZE} + 512))
+  local CUR_IMG_SIZE=$((${LINUX_PART_END} + 512))
+  local OBJ_IMG_SIZE=`du -sb ${IMG_PATH} | awk -F' ' '{ print $1 }'` # https://prowebmastering.ru/linux-uznat-razmer-papok-i-failov-v-terminale.html
 
-  echo "IMG_MIN_SIZE: $IMG_MIN_SIZE"
-  echo "CUR_IMG_SIZE: $CUR_IMG_SIZE"
-  echo "OBJ_IMG_SIZE: $OBJ_IMG_SIZE"
+  echo "IMG_MIN_SIZE: ${IMG_MIN_SIZE}"
+  echo "CUR_IMG_SIZE: ${CUR_IMG_SIZE}"
+  echo "OBJ_IMG_SIZE: ${OBJ_IMG_SIZE}"
 
-  if [[ -n $NEW_IMG_SIZE ]]; then
+  if [[ -n ${NEW_IMG_SIZE} ]]; then
       # FIXED:
       # losetup: os.img: Warning: file does not fit into a 512-byte sector; the end of the file will be ignored.
       DIVREMAINDER=$((${NEW_IMG_SIZE} % 512))
-      if [[ $DIVREMAINDER -gt 0 ]]; then
-          my_echo "The NEW_IMG_SIZE ($NEW_IMG_SIZE) does not fit in 512-byte sector (logic of losetup utility), autocorrect size." "BLUE"
-          NEW_IMG_SIZE=$(($NEW_IMG_SIZE + 512 - $DIVREMAINDER))
+      if [[ ${DIVREMAINDER} -gt 0 ]]; then
+          my_echo "The NEW_IMG_SIZE (${NEW_IMG_SIZE}) does not fit in 512-byte sector (logic of losetup utility), autocorrect size." "BLUE"
+          NEW_IMG_SIZE=$((${NEW_IMG_SIZE} + 512 - ${DIVREMAINDER}))
       fi
 
-      LINUX_PART_NEW_SIZE=$(($NEW_IMG_SIZE - $LINUX_PART_START - 512))
-      echo "LINUX_PART_NEW_SIZE: $LINUX_PART_NEW_SIZE"
+      LINUX_PART_NEW_SIZE=$((${NEW_IMG_SIZE} - ${LINUX_PART_START} - 512))
+      echo "LINUX_PART_NEW_SIZE: ${LINUX_PART_NEW_SIZE}"
       # Кажется можно и не делать дробные сектора для увеличения размера раздела,
       # но ввиду нестабильности и постоянных статических ошибок,
       # а также для унификации кода сделал перерасчет LINUX_PART_NEW_SIZE и NEW_IMG_SIZE
       # с учетом 4096-байтового сектора в LINUX_PART
       DIVREMAINDER2=$((${LINUX_PART_NEW_SIZE} % 4096))
-      if [[ $DIVREMAINDER2 -gt 0 ]]; then
-          my_echo "The LINUX_PART_NEW_SIZE ($LINUX_PART_NEW_SIZE) does not fit in 4096-byte sector (logic of resize2fs utility), autocorrect size. And NEW_IMG_SIZE ($NEW_IMG_SIZE) too." "BLUE"
-          LINUX_PART_NEW_SIZE=$(($LINUX_PART_NEW_SIZE + 4096 - $DIVREMAINDER2))
-          NEW_IMG_SIZE=$(($LINUX_PART_START + $LINUX_PART_NEW_SIZE + 512))
+      if [[ ${DIVREMAINDER2} -gt 0 ]]; then
+          my_echo "The LINUX_PART_NEW_SIZE (${LINUX_PART_NEW_SIZE}) does not fit in 4096-byte sector (logic of resize2fs utility), autocorrect size. And NEW_IMG_SIZE (${NEW_IMG_SIZE}) too." "BLUE"
+          LINUX_PART_NEW_SIZE=$((${LINUX_PART_NEW_SIZE} + 4096 - ${DIVREMAINDER2}))
+          NEW_IMG_SIZE=$((${LINUX_PART_START} + ${LINUX_PART_NEW_SIZE} + 512))
       fi
-      LINUX_PART_NEW_END=$(($LINUX_PART_START + $LINUX_PART_NEW_SIZE))
+      LINUX_PART_NEW_END=$((${LINUX_PART_START} + ${LINUX_PART_NEW_SIZE}))
 
-      echo "NEW_IMG_SIZE: $NEW_IMG_SIZE"
-      echo "LINUX_PART_NEW_SIZE: $LINUX_PART_NEW_SIZE"
-      echo "LINUX_PART_NEW_END: $LINUX_PART_NEW_END"
+      echo "NEW_IMG_SIZE: ${NEW_IMG_SIZE}"
+      echo "LINUX_PART_NEW_SIZE: ${LINUX_PART_NEW_SIZE}"
+      echo "LINUX_PART_NEW_END: ${LINUX_PART_NEW_END}"
 
       # https://andreyex.ru/operacionnaya-sistema-linux/kak-sravnivat-chisla-v-bash
-      [[ $NEW_IMG_SIZE -lt $IMG_MIN_SIZE ]] && (my_echo "The image size cannot be less then $IMG_MIN_SIZE" "RED"; exit 1)
-      [[ $NEW_IMG_SIZE -eq $CUR_IMG_SIZE ]] && (my_echo "Nothing to do" "GREEN"; exit 1)
+      [[ ${NEW_IMG_SIZE} -lt ${IMG_MIN_SIZE} ]] && (my_echo "The image size cannot be less then ${IMG_MIN_SIZE}" "RED"; exit 1)
+      [[ ${NEW_IMG_SIZE} -eq ${CUR_IMG_SIZE} ]] && (my_echo "Nothing to do" "GREEN"; exit 1)
 
       # https://blog.eaglenn.ru/izmenenie-razmera-razdela-ext2-ext3-ext4-bez-poteri-informatsii/
-      if [[ $NEW_IMG_SIZE -lt $CUR_IMG_SIZE ]]; then
+      if [[ ${NEW_IMG_SIZE} -lt ${CUR_IMG_SIZE} ]]; then
           echo "MIN"
 
-          LOOPBACK=$(losetup -f) && losetup -Pf $IMG_PATH
-          resize2fs ${LOOPBACK}p2 $((LINUX_PART_NEW_SIZE / 4096))
+          LOOPBACK=$(losetup -f) && losetup -Pf ${IMG_PATH}
+          resize2fs ${LOOPBACK}p2 $((${LINUX_PART_NEW_SIZE} / 4096))
           # Можно добавить параметр "-p" для отслеживания того, что делает программа.
           # Больше о параметрах здесь: http://man7.org/linux/man-pages/man8/resize2fs.8.html
           # Последним параметром указывается размер раздела,
           # если параметр не указан, то раздел увеличивается до последнего сектора устройства.
 
           sleep 1
-          losetup -d $LOOPBACK
+          losetup -d ${LOOPBACK}
 
-          parted $IMG_PATH rm 2
-          parted $IMG_PATH unit B mkpart primary $LINUX_PART_START $LINUX_PART_NEW_END
+          parted ${IMG_PATH} rm 2
+          parted ${IMG_PATH} unit B mkpart primary ${LINUX_PART_START} ${LINUX_PART_NEW_END}
 
           # https://linux.die.net/man/1/truncate
-          truncate -s $(($LINUX_PART_NEW_END + 512)) $IMG_PATH
+          truncate -s $((${LINUX_PART_NEW_END} + 512)) ${IMG_PATH}
       else
           echo "MAX"
 
-          truncate -s$NEW_IMG_SIZE $IMG_PATH
+          truncate -s${NEW_IMG_SIZE} ${IMG_PATH}
 
-          parted $IMG_PATH rm 2
-          parted $IMG_PATH unit B mkpart primary $LINUX_PART_START $LINUX_PART_NEW_END
+          parted ${IMG_PATH} rm 2
+          parted ${IMG_PATH} unit B mkpart primary ${LINUX_PART_START} ${LINUX_PART_NEW_END}
 
-          LOOPBACK=$(losetup -f) && losetup -Pf $IMG_PATH
+          LOOPBACK=$(losetup -f) && losetup -Pf ${IMG_PATH}
 
-          resize2fs ${LOOPBACK}p2 $((LINUX_PART_NEW_SIZE / 4096))
+          resize2fs ${LOOPBACK}p2 $((${LINUX_PART_NEW_SIZE} / 4096))
           sleep 1
-          losetup -d $LOOPBACK
+          losetup -d ${LOOPBACK}
       fi
 
       # More information
       echo "================================================================================"
-      parted -m $IMG_PATH unit B print free
+      parted -m ${IMG_PATH} unit B print free
       echo "================================================================================"
 
       mount_image ${IMG_PATH} fix_partuuid ${IMG_PATH} ${CUR_DISKID}
